In [1]:
import pandas as pd
import numpy as np
import datetime
import os

In [19]:
voucher_df = pd.read_excel('/Volumes/commons/PP-PROLOG/VENDOR_MANAGEMENT/Data_Analytics/Data_Files/Daily_Reports/PL_VOUCHER_PYMTS_PT7.xlsx')

In [20]:
voucher_df

,VCH - Dept ID,VCH - Activity Code,VCH - Voucher Acct,VCH - Mode,VCH - Voucher Business Unit,VCH - Work Order,VCH - Payroll Funct,VCH - Vendor Name,VCH - AP Unit,VCH - Vendor ID,...,CMS - Vchr Budgt Analyst FN,CMS - Vchr Budgt Analyst LN,CMS - Vchr WO Contract,VCH - FMIS Contract ID,CMS - Vchr MAC Code,CMS - Vchr Resp Code,CMS - Vchr CIP Code,CMS - Vchr CIP Status,CMS - Vchr CIP Descr,Query Date
0,841002,1.0,2110000,0,NaN,NaN,0,PASEK CORPORATION,OPER1,74237,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-18 21:54:59.540
1,841002,1.0,2110000,0,NaN,NaN,0,PASEK CORPORATION,OPER1,74237,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-18 21:54:59.540
2,841002,1.0,1112007,0,NaN,NaN,0,PASEK CORPORATION,OPER1,74237,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-18 21:54:59.540
3,841002,1.0,2124200,0,NaN,NaN,0,PASEK CORPORATION,OPER1,74237,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-18 21:54:59.540
4,841002,1.0,2110000,0,NaN,NaN,0,FIRE EQUIPMENT INC,CAPTL,46790,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-18 21:54:59.540
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186544,841002,1.0,1112007,0,NaN,NaN,0,TRILLIUM TECHNICAL,OPER1,114108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-18 21:54:59.540
186545,841002,1.0,2110000,0,NaN,NaN,0,TRILLIUM TECHNICAL,OPER1,114108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-18 21:54:59.540
186546,841002,1.0,2110000,0,NaN,NaN,0,TRILLIUM TECHNICAL,OPER1,114108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-18 21:54:59.540
186547,433002,1.0,6134099,2,NaN,NaN,0,TRILLIUM TECHNICAL,OPER1,114108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-18 21:54:59.540
186548,433002,1.0,6166650,2,NaN,NaN,0,TRILLIUM TECHNICAL,OPER1,114108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-18 21:54:59.540

In [21]:
# Change Types
voucher_df['VCH - Voucher Line No'] = voucher_df['VCH - Voucher Line No'].astype('str')
voucher_df['VCH - PO Line No'] = voucher_df['VCH - PO Line No'].astype('str')
voucher_df['VCH - PO Line Sched No'] = voucher_df['VCH - PO Line Sched No'].astype('str')
voucher_df['VCH - PO Distrib Line'] = voucher_df['VCH - PO Distrib Line'].astype('str')
voucher_df['VCH - Voucher Rcpt Line No'] = voucher_df['VCH - Voucher Rcpt Line No'].astype('str')

# Rename 
voucher_df.rename(columns={'Query Date': 'VCH - Query Date'}, inplace=True)

In [23]:
voucher_df['Calc - Vchr Amt Movement'] = np.where(voucher_df['VCH - Voucher Line Amt'] < 0, 'Neg(-1)', 'Pos(+)')
voucher_df['VCH - Fund'] = voucher_df.apply(lambda x: str(x['VCH - Fund']).rjust(2, '0'), axis=1)

In [24]:
voucher_df['CMS - Vchr Proj Code'].unique()

array([nan, 'R16', 'R18', 'Z92', 'A35', 'Z96', 'N03', 'A47', 'F64', 'Z94',
       'R19', 'D71', 'A43', 'J75', 'T27', 'V21', 'D44', 'M09', 'X39',
       'X17', 'C95', 'T20', 'V10', 'E22', 'A25', 'C14', 'J90', 'T62',
       'V90', 'P90', 'Z90', 'Z95', 'A08', 'K78', 'V30', 'V69', 'B94',
       'N93', 'Z79', 'D76', 'W43', 'B64', 'NCP', 'V51', 'V22', 'V70',
       'C20', 'Z00', 'V20', 'V40', 'R32', 'A92', 'P62', 'Z75', 'B91',
       'D99', 'C94', 'B22', 'G70', 'P02', 'X94', 'A46', 'R44', 'V50',
       'A01', 'L60', 'B45', 'G49', 'B90', 'C90', 'T40', 'W91', 'S01',
       'W46', 'Z29', 'C72', 'U90', 'A72', 'B92', 'X95', 'M43', 'Z97',
       'H32', 'T92', 'Y99', 'R17', 'C99', 'G60', 'M90', 'V29', 'R94',
       'Z93', 'V56', 'B73', 'Z99', 'H62', 'T24', 'Q60', 'A90', 'J74',
       'X90', 'C00', 'L70', 'P61', 'J19', 'P63', 'S02', 'V60', 'F11',
       'G64', 'T70', 'N69', 'A93', 'V09', 'T90', 'D15', 'X60', 'S43',
       'R98', 'K02', 'W92', 'X19', 'R54', 'R21', 'R90', 'D72', 'V03',
       'Y91', 'S99', 'D82', 'X49', 'T30', 'S17', 'A41', 'Q40', 'Y92',
       'A31', 'H77', 'W90', 'A27', 'D60', 'Z09', 'B43', 'Z91', 'R14',
       'D52', 'F60', 'P45', 'N02', 'V79', 'P42', 'D80', 'A34', 'Z19',
       'F91', 'G90', 'Z69', 'F90', 'S31', 'D05', 'Q90', 'X72', 'V85',
       'E79', 'J70', 'W47', 'A26', 'M20', 'I62', 'J66', 'T26', 'P35',
       'H92', 'S40', 'D53', 'D46', 'Q21', 'Q19', 'V02', 'N73', 'Z01',
       'S10', 'N39', 'C08', 'V18', 'A95', 'N53', 'N51', 'Q01', 'M48',
       'U19', 'S53', 'N50', 'C19', 'U15', 'A91', 'C29', 'X02', 'V48',
       'R15', 'D93', 'A62', 'Z02', 'A48', 'L72', 'D69', 'S32', 'P40',
       'G67', 'D43', 'C02', 'H74', 'D35', 'S03', 'V93', 'N20', 'X74',
       'P09', 'K74', 'G72', 'S27', 'F67', 'G09', 'X48', 'D42', 'N60',
       'X29', 'V00', 'M46', 'M12', 'A49', 'X15', 'X69', 'V99', 'A94',
       'X98', 'A12', 'R99', 'D37', 'D50', 'U92', 'V16', 'T25', 'X70',
       'N19', 'R02', 'D02', 'H63', 'N52', 'X13', 'P32', 'L74', 'X12',
       'M60'], dtype=object)

In [33]:
# More calculations
voucher_df['Table Names'] = 'CurrentYr_Voucher_Data_FY22'
#voucher_df.drop('VCH - Voucher Business Unit', axi)

wo_contract_thresh = [
    (voucher_df['CMS - Vchr WO Contract'].str.slice(start=4, stop=6) == 'PS'),
    (voucher_df['CMS - Vchr WO Contract'].str.slice(start=4, stop=6) == 'CN'),
    (voucher_df['CMS - Vchr WO Contract'].str.slice(start=4, stop=6) == 'PA'),
    (voucher_df['CMS - Vchr WO Contract'].str.slice(start=4, stop=6) == 'MP'),
    (voucher_df['CMS - Vchr WO Contract'].str.slice(start=4, stop=6) == 'RE'),
    (voucher_df['CMS - Vchr WO Contract'].str.slice(start=4, stop=6) == 'FA'),
    (voucher_df['CMS - Vchr WO Contract'].str.slice(start=4, stop=6) == 'EX'),
    (voucher_df['CMS - Vchr WO Contract'].str.slice(start=4, stop=6) == 'IN'),
    (voucher_df['CMS - Vchr WO Contract'].str.slice(start=4, stop=6) == 'XG'),
    (voucher_df['CMS - Vchr WO Contract'].str.slice(start=4, stop=6) == 'OT')
]

wo_contract_values = ['Professional Services', 'Construction', 'Project Administration',
                     'Material Procurement', 'Real Estate', 'Force Account', 'External Force Account',
                     'Inspection', 'Unallocated Contingency', 'Other']

voucher_df['CMS - Vchr WO Contract Type'] = np.select(wo_contract_thresh, wo_contract_values)

first_three_chars_of_wo_contract = voucher_df.apply(lambda x: str(x['CMS - Vchr WO Contract'])[0:2], axis=1)

# Simplest one
voucher_df['CMS - Vchr Proj Code'] = np.where(voucher_df['CMS - Vchr Proj Code'].isna(), 
                                              first_three_chars_of_wo_contract, 
                                              voucher_df['CMS - Vchr Proj Code'])

In [64]:
excluded_accounts = ['2124200', '2120200', '6166650', '4350000', '4450000', '5180100', '5210000',
                    '5220000', '5250000', '5260000', '5810000', '6133800', '6135300']

In [83]:
vouchers_no_accounting = voucher_df.copy(deep=True)

# Need to check the logic of this filter – not sure if it's correct. 
vouchers_no_accounting = vouchers_no_accounting.loc[~(vouchers_no_accounting['VCH - Dept ID'] == '841002')]
print(vouchers_no_accounting)
vouchers_no_accounting = vouchers_no_accounting.loc[~(vouchers_no_accounting['VCH - Voucher Acct'].isin(excluded_accounts))]
print(vouchers_no_accounting)
vouchers_no_accounting = vouchers_no_accounting.loc[~(vouchers_no_accounting['VCH - Dept ID'].isna())]
print(vouchers_no_accounting)

        VCH - Dept ID  VCH - Activity Code  VCH - Voucher Acct  VCH - Mode  \
0              841002                  1.0             2110000           0
1              841002                  1.0             2110000           0
2              841002                  1.0             1112007           0
3              841002                  1.0             2124200           0
4              841002                  1.0             2110000           0
...               ...                  ...                 ...         ...
186544         841002                  1.0             1112007           0
186545         841002                  1.0             2110000           0
186546         841002                  1.0             2110000           0
186547         433002                  1.0             6134099           2
186548         433002                  1.0             6166650           2

       VCH - Voucher Business Unit  VCH - Work Order  VCH - Payroll Funct  \
0                              NaN               NaN                    0
1                              NaN               NaN                    0
2                              NaN               NaN                    0
3                              NaN               NaN                    0
4                              NaN               NaN                    0
...                            ...               ...                  ...
186544                         NaN               NaN                    0
186545                         NaN               NaN                    0
186546                         NaN               NaN                    0
186547                         NaN               NaN                    0
186548                         NaN               NaN                    0

         VCH - Vendor Name VCH - AP Unit  VCH - Vendor ID  ...  \
0        PASEK CORPORATION         OPER1            74237  ...
1        PASEK CORPORATION         OPER1            74237  ...
2        PASEK CORPORATION         OPER1            74237  ...
3        PASEK CORPORATION         OPER1            74237  ...
4       FIRE EQUIPMENT INC         CAPTL            46790  ...
...                    ...           ...              ...  ...
186544  TRILLIUM TECHNICAL         OPER1           114108  ...
186545  TRILLIUM TECHNICAL         OPER1           114108  ...
186546  TRILLIUM TECHNICAL         OPER1           114108  ...
186547  TRILLIUM TECHNICAL         OPER1           114108  ...
186548  TRILLIUM TECHNICAL         OPER1           114108  ...

        VCH - FMIS Contract ID CMS - Vchr MAC Code CMS - Vchr Resp Code  \
0                          NaN                 NaN                  NaN
1                          NaN                 NaN                  NaN
2                          NaN                 NaN                  NaN
3                          NaN                 NaN                  NaN
4                          NaN                 NaN                  NaN
...                        ...                 ...                  ...
186544                     NaN                 NaN                  NaN
186545                     NaN                 NaN                  NaN
186546                     NaN                 NaN                  NaN
186547                     NaN                 NaN                  NaN
186548                     NaN                 NaN                  NaN

       CMS - Vchr CIP Code CMS - Vchr CIP Status CMS - Vchr CIP Descr  \
0                      NaN                   NaN                  NaN
1                      NaN                   NaN                  NaN
2                      NaN                   NaN                  NaN
3                      NaN                   NaN                  NaN
4                      NaN                   NaN                  NaN
...                    ...                   ...                  ...
186544                 NaN                   NaN                  NaN
186545                 NaN                   NaN                  NaN
186546                 NaN                   NaN                  NaN
186547                 NaN                   NaN                  NaN
186548                 NaN                   NaN                  NaN

              VCH - Query Date  Calc - Vchr Amt Movement  \
0      2022-04-18 21:54:59.540                   Neg(-1)
1      2022-04-18 21:54:59.540                    Pos(+)
2      2022-04-18 21:54:59.540                   Neg(-1)
3      2022-04-18 21:54:59.540                    Pos(+)
4      2022-04-18 21:54:59.540                   Neg(-1)
...                        ...                       ...
186544 2022-04-18 21:54:59.540                   Neg(-1)
186545 2022-04-18 21:54:59.540                    Pos(+)
186546 2022-04-18 21:54:59.540                   Neg(-1)
186547 2022-04-18 21:54:59.540                    Pos(+)
186548 2022-04-18 21:54:59.540                   Neg(-1)

                        Table Names CMS - Vchr WO Contract Type
0       CurrentYr_Voucher_Data_FY22                           0
1       CurrentYr_Voucher_Data_FY22                           0
2       CurrentYr_Voucher_Data_FY22                           0
3       CurrentYr_Voucher_Data_FY22                           0
4       CurrentYr_Voucher_Data_FY22                           0
...                             ...                         ...
186544  CurrentYr_Voucher_Data_FY22                           0
186545  CurrentYr_Voucher_Data_FY22                           0
186546  CurrentYr_Voucher_Data_FY22                           0
186547  CurrentYr_Voucher_Data_FY22                           0
186548  CurrentYr_Voucher_Data_FY22                           0

[186549 rows x 78 columns]
        VCH - Dept ID  VCH - Activity Code  VCH - Voucher Acct  VCH - Mode  \
0              841002                  1.0             2110000           0
1              841002                  1.0             2110000           0
2              841002                  1.0             1112007           0
3              841002                  1.0             2124200           0
4              841002                  1.0             2110000           0
...               ...                  ...                 ...         ...
186544         841002                  1.0             1112007           0
186545         841002                  1.0             2110000           0
186546         841002                  1.0             2110000           0
186547         433002                  1.0             6134099           2
186548         433002                  1.0             6166650           2

       VCH - Voucher Business Unit  VCH - Work Order  VCH - Payroll Funct  \
0                              NaN               NaN                    0
1                              NaN               NaN                    0
2                              NaN               NaN                    0
3                              NaN               NaN                    0
4                              NaN               NaN                    0
...                            ...               ...                  ...
186544                         NaN               NaN                    0
186545                         NaN               NaN                    0
186546                         NaN               NaN                    0
186547                         NaN               NaN                    0
186548                         NaN               NaN                    0

         VCH - Vendor Name VCH - AP Unit  VCH - Vendor ID  ...  \
0        PASEK CORPORATION         OPER1            74237  ...
1        PASEK CORPORATION         OPER1            74237  ...
2        PASEK CORPORATION         OPER1            74237  ...
3        PASEK CORPORATION         OPER1            74237  ...
4       FIRE EQUIPMENT INC         CAPTL            46790  ...
...                    ...           ...              ...  ...
186544  TRILLIUM TECHNICAL         OPER1           114108  ...
186545  TRILLIUM TECHNICAL         OPER1           114108  ...
186546  TRILLIUM TECHNICAL         OPER1           114108  ...
186547  TRILLIUM TECHNICAL         OPER1           114108  ...
186548  TRILLIUM TECHNICAL         OPER1           114108  ...

        VCH - FMIS Contract ID CMS - Vchr MAC Code CMS - Vchr Resp Code  \
0                          NaN                 NaN                  NaN
1                          NaN                 NaN                  NaN
2                          NaN                 NaN                  NaN
3                          NaN                 NaN                  NaN
4                          NaN                 NaN                  NaN
...                        ...                 ...                  ...
186544                     NaN                 NaN                  NaN
186545                     NaN                 NaN                  NaN
186546                     NaN                 NaN                  NaN
186547                     NaN                 NaN                  NaN
186548                     NaN                 NaN                  NaN

       CMS - Vchr CIP Code CMS - Vchr CIP Status CMS - Vchr CIP Descr  \
0                      NaN                   NaN                  NaN
1                      NaN                   NaN                  NaN
2                      NaN                   NaN                  NaN
3                      NaN                   NaN                  NaN
4                      NaN                   NaN                  NaN
...                    ...                   ...                  ...
186544                 NaN                   NaN                  NaN
186545                 NaN                   NaN                  NaN
186546                 NaN                   NaN                  NaN
186547                 NaN                   NaN                  NaN
186548                 NaN                   NaN                  NaN

              VCH - Query Date  Calc - Vchr Amt Movement  \
0      2022-04-18 21:54:59.540                   Neg(-1)
1      2022-04-18 21:54:59.540                    Pos(+)
2      2022-04-18 21:54:59.540                   Neg(-1)
3      2022-04-18 21:54:59.540                    Pos(+)
4      2022-04-18 21:54:59.540                   Neg(-1)
...                        ...                       ...
186544 2022-04-18 21:54:59.540                   Neg(-1)
186545 2022-04-18 21:54:59.540                    Pos(+)
186546 2022-04-18 21:54:59.540                   Neg(-1)
186547 2022-04-18 21:54:59.540                    Pos(+)
186548 2022-04-18 21:54:59.540                   Neg(-1)

                        Table Names CMS - Vchr WO Contract Type
0       CurrentYr_Voucher_Data_FY22                           0
1       CurrentYr_Voucher_Data_FY22                           0
2       CurrentYr_Voucher_Data_FY22                           0
3       CurrentYr_Voucher_Data_FY22                           0
4       CurrentYr_Voucher_Data_FY22                           0
...                             ...                         ...
186544  CurrentYr_Voucher_Data_FY22                           0
186545  CurrentYr_Voucher_Data_FY22                           0
186546  CurrentYr_Voucher_Data_FY22                           0
186547  CurrentYr_Voucher_Data_FY22                           0
186548  CurrentYr_Voucher_Data_FY22                           0

[186549 rows x 78 columns]

        VCH - Dept ID  VCH - Activity Code  VCH - Voucher Acct  VCH - Mode  \
0              841002                  1.0             2110000           0
1              841002                  1.0             2110000           0
2              841002                  1.0             1112007           0
3              841002                  1.0             2124200           0
4              841002                  1.0             2110000           0
...               ...                  ...                 ...         ...
186544         841002                  1.0             1112007           0
186545         841002                  1.0             2110000           0
186546         841002                  1.0             2110000           0
186547         433002                  1.0             6134099           2
186548         433002                  1.0             6166650           2

       VCH - Voucher Business Unit  VCH - Work Order  VCH - Payroll Funct  \
0                              NaN               NaN                    0
1                              NaN               NaN                    0
2                              NaN               NaN                    0
3                              NaN               NaN                    0
4                              NaN               NaN                    0
...                            ...               ...                  ...
186544                         NaN               NaN                    0
186545                         NaN               NaN                    0
186546                         NaN               NaN                    0
186547                         NaN               NaN                    0
186548                         NaN               NaN                    0

         VCH - Vendor Name VCH - AP Unit  VCH - Vendor ID  ...  \
0        PASEK CORPORATION         OPER1            74237  ...
1        PASEK CORPORATION         OPER1            74237  ...
2        PASEK CORPORATION         OPER1            74237  ...
3        PASEK CORPORATION         OPER1            74237  ...
4       FIRE EQUIPMENT INC         CAPTL            46790  ...
...                    ...           ...              ...  ...
186544  TRILLIUM TECHNICAL         OPER1           114108  ...
186545  TRILLIUM TECHNICAL         OPER1           114108  ...
186546  TRILLIUM TECHNICAL         OPER1           114108  ...
186547  TRILLIUM TECHNICAL         OPER1           114108  ...
186548  TRILLIUM TECHNICAL         OPER1           114108  ...

        VCH - FMIS Contract ID CMS - Vchr MAC Code CMS - Vchr Resp Code  \
0                          NaN                 NaN                  NaN
1                          NaN                 NaN                  NaN
2                          NaN                 NaN                  NaN
3                          NaN                 NaN                  NaN
4                          NaN                 NaN                  NaN
...                        ...                 ...                  ...
186544                     NaN                 NaN                  NaN
186545                     NaN                 NaN                  NaN
186546                     NaN                 NaN                  NaN
186547                     NaN                 NaN                  NaN
186548                     NaN                 NaN                  NaN

       CMS - Vchr CIP Code CMS - Vchr CIP Status CMS - Vchr CIP Descr  \
0                      NaN                   NaN                  NaN
1                      NaN                   NaN                  NaN
2                      NaN                   NaN                  NaN
3                      NaN                   NaN                  NaN
4                      NaN                   NaN                  NaN
...                    ...                   ...                  ...
186544                 NaN                   NaN                  NaN
186545                 NaN                   NaN                  NaN
186546                 NaN                   NaN                  NaN
186547                 NaN                   NaN                  NaN
186548                 NaN                   NaN                  NaN

              VCH - Query Date  Calc - Vchr Amt Movement  \
0      2022-04-18 21:54:59.540                   Neg(-1)
1      2022-04-18 21:54:59.540                    Pos(+)
2      2022-04-18 21:54:59.540                   Neg(-1)
3      2022-04-18 21:54:59.540                    Pos(+)
4      2022-04-18 21:54:59.540                   Neg(-1)
...                        ...                       ...
186544 2022-04-18 21:54:59.540                   Neg(-1)
186545 2022-04-18 21:54:59.540                    Pos(+)
186546 2022-04-18 21:54:59.540                   Neg(-1)
186547 2022-04-18 21:54:59.540                    Pos(+)
186548 2022-04-18 21:54:59.540                   Neg(-1)

                        Table Names CMS - Vchr WO Contract Type
0       CurrentYr_Voucher_Data_FY22                           0
1       CurrentYr_Voucher_Data_FY22                           0
2       CurrentYr_Voucher_Data_FY22                           0
3       CurrentYr_Voucher_Data_FY22                           0
4       CurrentYr_Voucher_Data_FY22                           0
...                             ...                         ...
186544  CurrentYr_Voucher_Data_FY22                           0
186545  CurrentYr_Voucher_Data_FY22                           0
186546  CurrentYr_Voucher_Data_FY22                           0
186547  CurrentYr_Voucher_Data_FY22                           0
186548  CurrentYr_Voucher_Data_FY22                           0

[186549 rows x 78 columns]

In [85]:
vouchers_no_accounting['Acctg Entry Filter'] = 'Standard Expense Accts'

TODO: do flow 2b and 2c (should be easy).

### Flow 2B

In [93]:
vouchers_2b_df = vouchers_no_accounting.copy(deep=True)

vch_columns_to_remove = ['Filter Acctg Entries', 'VCHR - Contract ID', 'CMS - WO Contract Type', 'VCH - Dept/Loc',
                    'VCH - Voucher Grant ID', 'VCH - Voucher Work Order', 'CMS - Proj WO Status', 'CMS - Proj Code',
                    'CMS - WO Descr', 'CMS - WO Date Closed', 'CMS - Estimate', 'CMS - Comitd Funds',
                    'CMS - Apprvd Amt', 'CMS - WO LTD Exp', 'CMS - Import Date', 'CMS - Budget Analyst FN',
                    'CMS - Budget Analyst LN', 'CMS - WO Contract', 'VCHR - FMIS Contract ID', 
                    # Second removal starts here
                    'CMS - Vchr WO Contract Type', 'Acctg Entry Filter', 'Acctg Dept Only', 'Calc - Vchr Amt Movement',
                    'Table Names', 'VCH - Activity Code', 'VCH - Voucher Acct', 'VCH - Mode', 'VCH - Payroll Funct',
                    'VCH - Vendor Name', 'VCH - AP Unit', 'VCH - Vendor ID', 'Vchr_ID', 'VCH - PO No', 
                    'VCH - Invoice No', 'VCH - Invoice Date', 'VCH - Business Unit GL', 'VCH - Journal ID',
                    'VCH - Journal Date', 'VCH - Voucher Line Amt', 'VCH - Ctrl Group ID', 'VCH - Fund',
                    'VCH - Acctg Date', 'VCH - User Rcvd Date', 'VCH - Invoice Dute Date', 'VCH - Discount Due Date',
                    'VCH - Vendor Short Name', 'Vchr_Line_No', 'VCH - PO Line No', 'VCH - PO Line Sched No',
                    'VCH - PO Distrib Line', 'VCH - PO Line Descr', 'VCH - Voucher Qty', 'VCH - Voucher UOM',
                    'VCH - Voucher Unit Price', 'VCH - Match Line Option', 'VCH - Amt Only Flag',
                    'VCH - Voucher Rcpt No', 'Vhr_Rcpt_Line_No', 'VCH - Vendor Short Name USR', 'VCH - Vendor Class',
                    'VCH - Old Vendor ID No', 'VCH - Last Activity Date', 'VCH - Vendor Status', 'VCH - Voucher Type',
                    'VCH - Origin Code', 'VCH - PO Business Unit', 'VCH - Related Voucher', 'VCH - Discount Amt',
                    'VCH - Override', 'VCH - Override User ID', 'VCH - Override Date', 'VCH - Receipt Rcvd Date',
                    'VCH - Acctg Period', 'VCH - Vchr Fiscal Year', 'VCH - Query Date', 'VCH - Dept ID', 
                    'CMS - Vchr Grant ID', 'VCH - Work Order', 'CMS - Vchr Proj WO Status', 'CMS - Vchr Proj Code',
                    'CMS - Vchr WO Descr', 'CMS - Vchr Grant Descr', 'CMS - Vchr Project Descr', 
                    'CMS - Vchr WO Date Closed', 'CMS - Vchr WO Curr Estimate', 'CMS - Vchr WO Commitd Funds',
                    'CMS - Vchr WO Apprvd Amt', 'CMS - Vchr WO LTD Exp', 'CMS - Vchr Import Date', 'CMS - Vchr Budget Analyst FN',
                    'CMS - Vchr Budget Analyst LN', 'CMS - Vchr WO Contract', 'VCH - FMIS Contract ID',
                    'CMS - Vchr MAC Code', 'CMS - Vchr Resp Code', 'CMS - Vchr CIP Code', 'CMS - Vchr CIP Status',
                    'CMS - Vchr CIP Descr']

In [94]:
vouchers_no_accounting.drop(vch_columns_to_remove, axis=1, errors='ignore')

,VCH - Voucher Business Unit,VCH - Voucher ID,VCH - Invoice Due Date,VCH - Voucher Line No,VCH - Voucher Rcpt Line No,CMS - Vchr WO Comitd Funds,CMS - Vchr Budgt Analyst FN,CMS - Vchr Budgt Analyst LN
0,NaN,865896,2021-08-15 00:00:00,1,0,0.0,NaN,NaN
1,NaN,865896,2021-08-15 00:00:00,1,0,0.0,NaN,NaN
2,NaN,865896,2021-08-15 00:00:00,1,0,0.0,NaN,NaN
3,NaN,865896,2021-08-15 00:00:00,1,0,0.0,NaN,NaN
4,NaN,97946,2021-08-14 00:00:00,1,1,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...
186544,NaN,886522,2022-03-03 00:00:00,1,0,0.0,NaN,NaN
186545,NaN,886522,2022-03-03 00:00:00,1,0,0.0,NaN,NaN
186546,NaN,886522,2022-03-03 00:00:00,1,0,0.0,NaN,NaN
186547,NaN,886522,2022-03-03 00:00:00,1,0,0.0,NaN,NaN
186548,NaN,886522,2022-03-03 00:00:00,1,0,0.0,NaN,NaN

In [ ]:
# The renames are meaningless, because we're joining on them.

For super complex calculated fields: 
- take the endpoints and see it at a business level.